#!/bin/bash --norc
#PBS -S /bin/bash
#PBS -V
#PBS -N reprocess_detections
#PBS -q cores24
#PBS -l nodes=1:ppn=24,walltime=99:00:00
#PBS -r n
#PBS -k oe
module purge
module load python
source activate astrotog_hpc
cd /home/csetzer/LSST

echo $PBS_O_WORKDIR
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:

#!Create a machine file
cat $PBS_NODEFILE | uniq > /home/csetzer/LSST/astrotog_output/machine.file.$PBS_JOBID
echo PBS_NODEFILE=$PBS_NODEFILE

export PYTHONPATH=$PYTHONPATH:/home/csetzer/.conda/envs/astrotog_hpc/bin/python

python reprocess_detections.py
